export const DEMANDE_INTERVENTION_STATUTS = {
  EN_PREPARATION: 'EN_PREPARATION',
  ATTENTE_PRISE_EN_COMPTE: 'ATTENTE_PRISE_EN_COMPTE',
  ATTENTE_REALISATION: 'ATTENTE_REALISATION',
  TERMINE: 'TERMINE',
  REFUSE: 'REFUSE',
  SOLDE: 'SOLDE',
  ANNULE: 'ANNULE',
} as const;

export type DemandeInterventionStatut =
  (typeof DEMANDE_INTERVENTION_STATUTS)[keyof typeof DEMANDE_INTERVENTION_STATUTS];