export const INTERVENTION_ETATS = {
  EN_PREPARATION: 'EN_PREPARATION',
  ATTENTE_DEVIS: 'ATTENTE_DEVIS',
  ATTENTE_VALIDATION: 'ATTENTE_VALIDATION',
  ATTENTE_FOURNITURE: 'ATTENTE_FOURNITURE',
  ATTENTE_REALISATION: 'ATTENTE_REALISATION',
  EN_COURS: 'EN_COURS',
  TERMINE: 'TERMINE',
  SOLDE: 'SOLDE',
  ARCHIVE: 'ARCHIVE',
  ANNULE: 'ANNULE',
} as const;

export type InterventionEtat =
  (typeof INTERVENTION_ETATS)[keyof typeof INTERVENTION_ETATS];

export const INTERVENTION_TYPES = {
  CORRECTIF: 'CORRECTIF',
  PREVENTIF: 'PREVENTIF',
  CONDITIONNEL: 'CONDITIONNEL',
} as const;